# Generated by Django 4.2.7 on 2026-03-31 17:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loja', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='icone',
            field=models.CharField(blank=True, default='', help_text='Opcional - emoji para representar a categoria', max_length=10, verbose_name='Icone (emoji)'),
        ),
    ]
