# Generated by Django 4.2.7 on 2026-03-31 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0002_pedido_usuario_alter_categoria_icone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itempedido',
            name='pedido',
        ),
        migrations.RemoveField(
            model_name='itempedido',
            name='produto',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='usuario',
        ),
        migrations.AlterField(
            model_name='categoria',
            name='icone',
            field=models.CharField(blank=True, default='', help_text='Opcional', max_length=10, verbose_name='Icone'),
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='ItemPedido',
        ),
        migrations.DeleteModel(
            name='Pedido',
        ),
    ]
