# Generated by Django 4.2.7 on 2026-04-01 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0003_remove_itempedido_pedido_remove_itempedido_produto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='icone',
            field=models.CharField(blank=True, default='', help_text='Opcional — use um emoji, ex: 🍦', max_length=10, verbose_name='Icone'),
        ),
    ]
